# .smithery/deploy.yaml
apiVersion: smithery.ai/v1
kind: Deployment
metadata:
  name: liquidation-tracker
  
spec:
  # Deployment configuration
  replicas: 1
  
  # Container configuration
  container:
    image: liquidation-tracker:latest
    port: 8000
    
    # Resource limits
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
        
    # Environment variables
    env:
      - name: DISPLAY
        value: ":99"
      - name: DBUS_SESSION_BUS_ADDRESS
        value: "/dev/null"
      - name: CHROME_BIN
        value: "/usr/bin/google-chrome"
        
    # Health check
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 30
      
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
      
  # Service configuration
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    
  # Ingress (if needed)
  # ingress:
  #   enabled: true
  #   host: liquidation-tracker.yourdomain.com
  #   tls: true